#!/usr/bin/env python3
"""Audit and extract exclusions from public-business-research workbooks."""

from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from collections import Counter, defaultdict
from pathlib import Path
from urllib.parse import urlparse

try:
    from openpyxl import load_workbook
except ImportError as exc:  # pragma: no cover - environment-specific
    raise SystemExit(
        "openpyxl is required. Use the Codex bundled spreadsheet Python runtime "
        "or install openpyxl in the active environment."
    ) from exc


GENERATOR = "public-business-research"
SCHEMA_VERSION = "1"
COMPANY_SHEET = "Companies"
META_SHEET = "_meta"

REQUIRED_HEADERS = [
    "Company Name",
    "Country",
    "City",
    "Official Website",
    "Root Domain",
    "Public Email",
    "Public Phone",
    "Public WhatsApp",
    "Contact Name",
    "Contact Title",
    "Contact Tier",
    "Contact Source URL",
    "Source Type",
    "Website Signals",
    "Pain-Point Hypotheses",
    "Recommended Sales Angle",
    "English Outreach Opener",
    "Verified On",
    "Manual Recheck",
    "Notes",
]

NONEMPTY_HEADERS = [
    "Company Name",
    "Country",
    "Official Website",
    "Root Domain",
    "Public Email",
    "Contact Tier",
    "Contact Source URL",
    "Source Type",
    "Website Signals",
    "Pain-Point Hypotheses",
    "Recommended Sales Angle",
    "English Outreach Opener",
    "Verified On",
    "Manual Recheck",
]

EMAIL_RE = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
COMPANY_SUFFIXES = {
    "co",
    "company",
    "corp",
    "corporation",
    "inc",
    "incorporated",
    "limited",
    "ltd",
    "llc",
    "plc",
    "pty",
}


def clean(value: object) -> str:
    return "" if value is None else str(value).strip()


def normalize_email(value: object) -> str:
    raw = clean(value).lower()
    if not raw:
        return ""
    return re.split(r"[;,\s]+", raw)[0]


def normalize_domain(value: object) -> str:
    raw = clean(value).lower()
    if not raw:
        return ""
    candidate = raw if "://" in raw else f"https://{raw}"
    host = (urlparse(candidate).hostname or "").lower().rstrip(".")
    return host[4:] if host.startswith("www.") else host


def normalize_company(value: object) -> str:
    raw = unicodedata.normalize("NFKC", clean(value)).casefold()
    text = " ".join("".join(character if character.isalnum() else " " for character in raw).split())
    words = [word for word in text.split() if word not in COMPANY_SUFFIXES]
    return " ".join(words)


def is_http_url(value: object) -> bool:
    parsed = urlparse(clean(value))
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def workbook_meta(workbook) -> dict[str, str]:
    if META_SHEET not in workbook.sheetnames:
        return {}
    sheet = workbook[META_SHEET]
    return {
        clean(row[0].value): clean(row[1].value)
        for row in sheet.iter_rows(min_row=1, max_col=2)
        if clean(row[0].value)
    }


def is_marked_workbook(path: Path) -> bool:
    try:
        workbook = load_workbook(path, read_only=True, data_only=True)
        return workbook_meta(workbook).get("generated_by") == GENERATOR
    except Exception:
        return False


def read_company_rows(path: Path) -> tuple[dict[str, str], list[dict[str, str]]]:
    workbook = load_workbook(path, read_only=True, data_only=True)
    meta = workbook_meta(workbook)
    if meta.get("generated_by") != GENERATOR:
        raise ValueError("workbook is not marked as generated by this skill")
    if COMPANY_SHEET not in workbook.sheetnames:
        raise ValueError(f"missing {COMPANY_SHEET!r} sheet")

    sheet = workbook[COMPANY_SHEET]
    values = sheet.iter_rows(values_only=True)
    try:
        raw_headers = next(values)
    except StopIteration as exc:
        raise ValueError("Companies sheet is empty") from exc

    headers = [clean(value) for value in raw_headers]
    rows: list[dict[str, str]] = []
    for raw_row in values:
        record = {
            headers[index]: clean(value)
            for index, value in enumerate(raw_row)
            if index < len(headers) and headers[index]
        }
        if record.get("Company Name"):
            rows.append(record)
    return meta, rows


def identity(record: dict[str, str]) -> dict[str, str]:
    return {
        "company": normalize_company(record.get("Company Name")),
        "domain": normalize_domain(
            record.get("Root Domain") or record.get("Official Website")
        ),
        "email": normalize_email(record.get("Public Email")),
    }


def marked_workbooks(root: Path, excluded: set[Path]) -> list[Path]:
    paths: list[Path] = []
    for pattern in ("*.xlsx", "*.xlsm"):
        for path in root.rglob(pattern):
            resolved = path.resolve()
            if resolved in excluded or path.name.startswith("~$"):
                continue
            if is_marked_workbook(path):
                paths.append(path)
    return sorted(set(paths))


def collect_exclusions(
    root: Path, excluded: set[Path], additional: list[Path] | None = None
) -> dict[str, object]:
    records: list[dict[str, str]] = []
    sources: list[str] = []
    paths = marked_workbooks(root, excluded)
    for path in additional or []:
        resolved = path.resolve()
        if resolved not in excluded and path.exists() and is_marked_workbook(path):
            paths.append(path)
    for path in sorted(set(paths)):
        try:
            _, rows = read_company_rows(path)
        except Exception:
            continue
        sources.append(str(path.resolve()))
        for row in rows:
            item = identity(row)
            item["source_workbook"] = str(path.resolve())
            item["display_name"] = row.get("Company Name", "")
            records.append(item)
    return {
        "generator": GENERATOR,
        "root": str(root.resolve()),
        "workbooks_scanned": len(sources),
        "companies_seen": len(records),
        "source_workbooks": sources,
        "records": records,
    }


def duplicate_values(records: list[dict[str, str]], key: str) -> dict[str, list[int]]:
    positions: dict[str, list[int]] = defaultdict(list)
    for index, record in enumerate(records, start=2):
        value = identity(record)[key]
        if value:
            positions[value].append(index)
    return {value: rows for value, rows in positions.items() if len(rows) > 1}


def audit(
    path: Path, root: Path, expected: int, prior_workbooks: list[Path] | None = None
) -> dict[str, object]:
    errors: list[str] = []
    warnings: list[str] = []
    try:
        workbook = load_workbook(path, read_only=False, data_only=True)
    except Exception as exc:
        return {"passed": False, "errors": [f"cannot open workbook: {exc}"]}

    meta = workbook_meta(workbook)
    for key in (
        "generated_by",
        "schema_version",
        "product",
        "target_customer",
        "sales_market",
        "batch_size",
        "created_at",
    ):
        if not meta.get(key):
            errors.append(f"_meta is missing {key!r}")
    if meta.get("generated_by") and meta["generated_by"] != GENERATOR:
        errors.append("_meta generated_by has the wrong value")
    if meta.get("schema_version") and meta["schema_version"] != SCHEMA_VERSION:
        errors.append("unsupported schema_version")
    if META_SHEET in workbook.sheetnames and workbook[META_SHEET].sheet_state != "hidden":
        warnings.append("_meta sheet is not hidden")

    if COMPANY_SHEET not in workbook.sheetnames:
        errors.append(f"missing {COMPANY_SHEET!r} sheet")
        return {"passed": False, "errors": errors, "warnings": warnings}

    sheet = workbook[COMPANY_SHEET]
    headers = [clean(cell.value) for cell in sheet[1]]
    missing_headers = [header for header in REQUIRED_HEADERS if header not in headers]
    if missing_headers:
        errors.append(f"missing headers: {', '.join(missing_headers)}")

    rows: list[dict[str, str]] = []
    for raw_row in sheet.iter_rows(min_row=2, values_only=True):
        record = {
            headers[index]: clean(value)
            for index, value in enumerate(raw_row)
            if index < len(headers) and headers[index]
        }
        if record.get("Company Name"):
            rows.append(record)

    if len(rows) != expected:
        errors.append(f"expected {expected} companies, found {len(rows)}")
    if meta.get("batch_size") and meta["batch_size"] != str(expected):
        errors.append(f"_meta batch_size must be {expected}")

    for index, row in enumerate(rows, start=2):
        for header in NONEMPTY_HEADERS:
            if not row.get(header):
                errors.append(f"row {index}: {header} is empty")
        email = normalize_email(row.get("Public Email"))
        if email and not EMAIL_RE.fullmatch(email):
            errors.append(f"row {index}: invalid Public Email")
        if row.get("Official Website") and not is_http_url(row["Official Website"]):
            errors.append(f"row {index}: invalid Official Website URL")
        if row.get("Contact Source URL") and not is_http_url(row["Contact Source URL"]):
            errors.append(f"row {index}: invalid Contact Source URL")
        if row.get("Contact Tier") and row["Contact Tier"].upper() not in {"A", "B", "C"}:
            errors.append(f"row {index}: Contact Tier must be A, B, or C")
        if row.get("Verified On") and not DATE_RE.fullmatch(row["Verified On"]):
            errors.append(f"row {index}: Verified On must be YYYY-MM-DD")
        if row.get("Manual Recheck") and row["Manual Recheck"].title() not in {"Yes", "No"}:
            errors.append(f"row {index}: Manual Recheck must be Yes or No")
        domain = normalize_domain(row.get("Root Domain"))
        website_domain = normalize_domain(row.get("Official Website"))
        related_domains = (
            domain == website_domain
            or website_domain.endswith(f".{domain}")
            or domain.endswith(f".{website_domain}")
        )
        if domain and website_domain and not related_domains:
            errors.append(f"row {index}: Root Domain does not match Official Website")

    for key in ("company", "domain", "email"):
        duplicates = duplicate_values(rows, key)
        for value, row_numbers in duplicates.items():
            errors.append(
                f"within-batch duplicate {key} {value!r} on rows "
                + ", ".join(map(str, row_numbers))
            )

    current = path.resolve()
    previous = collect_exclusions(root, {current}, prior_workbooks)
    excluded_indexes = {
        key: {record[key] for record in previous["records"] if record.get(key)}
        for key in ("company", "domain", "email")
    }
    for index, row in enumerate(rows, start=2):
        current_identity = identity(row)
        for key, prior_values in excluded_indexes.items():
            value = current_identity[key]
            if value and value in prior_values:
                errors.append(f"row {index}: matches earlier skill workbook by {key}: {value}")

    tiers = Counter(row.get("Contact Tier", "").upper() for row in rows)
    rechecks = sum(row.get("Manual Recheck", "").title() == "Yes" for row in rows)
    return {
        "passed": not errors,
        "workbook": str(path.resolve()),
        "company_count": len(rows),
        "tier_counts": {tier: tiers.get(tier, 0) for tier in ("A", "B", "C")},
        "manual_recheck_count": rechecks,
        "earlier_workbooks_scanned": previous["workbooks_scanned"],
        "earlier_companies_seen": previous["companies_seen"],
        "errors": errors,
        "warnings": warnings,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Audit and deduplicate public-business-research workbooks."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    exclusions_parser = subparsers.add_parser(
        "exclusions", help="list identities from earlier marked workbooks"
    )
    exclusions_parser.add_argument("--root", type=Path, required=True)
    exclusions_parser.add_argument(
        "--exclude", type=Path, action="append", default=[], help="workbook to omit"
    )
    exclusions_parser.add_argument(
        "--include",
        type=Path,
        action="append",
        default=[],
        help="additional marked workbook outside the root to include",
    )

    audit_parser = subparsers.add_parser("audit", help="audit one completed workbook")
    audit_parser.add_argument("workbook", type=Path)
    audit_parser.add_argument("--root", type=Path, required=True)
    audit_parser.add_argument("--expected", type=int, default=50)
    audit_parser.add_argument(
        "--prior",
        type=Path,
        action="append",
        default=[],
        help="additional marked workbook to treat as earlier research",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.root.exists() or not args.root.is_dir():
        print(json.dumps({"passed": False, "errors": ["root is not a directory"]}, indent=2))
        return 2

    if args.command == "exclusions":
        excluded = {path.resolve() for path in args.exclude}
        result = collect_exclusions(args.root, excluded, args.include)
        print(json.dumps(result, indent=2, ensure_ascii=False))
        return 0

    if not args.workbook.exists():
        print(json.dumps({"passed": False, "errors": ["workbook does not exist"]}, indent=2))
        return 2
    result = audit(args.workbook, args.root, args.expected, args.prior)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0 if result.get("passed") else 1


if __name__ == "__main__":
    sys.exit(main())
